

baseURL = "http://example.org/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Morgan Button"                        # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码
disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "Morgan"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 20
  identifier = "blog"
  url = "/tags/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Video"
  weight = 40
  identifier = "video"
  url = "/tags/video"
[[menu.main]]
  name = "3D"
  weight = 40
  identifier = "3D"
  url = "/tags/3D"
[[menu.main]]
  name = "Code"
  weight = 40
  identifier = "code"
  url = "/tags/code"

[params]
  subTitle = "My Portfolio/Blog Site"                                       # site's subTitle              # 网站二级标题
  footerSlogan = " "                                   # site's footer slogan         # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]                                   # site's keywords              # 网站关键字
  description = "Hugo theme zozo example site."                        # site's description           # 网站描述
  enableMathJax = true                                                 # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your social's url
# 社交地址配置
[social]
  github = "https://github.com/morganbutton"
  linkedin = "https://www.linkedin.com/in/morganbutton/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
